<?php
/**
 * List of available Schema.org types.
 * This file is automatically generated. Please do not edit this file directly.
 *
 * @package     posterno-schema
 * @copyright   Copyright (c) 2018, Pressmodo, LLC
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

/**
 * Retrieve the list of available schema.
 *
 * @return array
 */
function pno_get_schema_list() {

	$available_types = [
		'Action',
		'CreativeWork',
		'Event',
		'Intangible',
		'Organization',
		'Person',
		'Place',
		'Product',
	];

	return $available_types;

}

